[pytest]
# Configurações padrão de execução
addopts = -v -n auto --html=e2e/reports/report.html --self-contained-html --junitxml=e2e/reports/pytest-report.xml

markers =
    cadastro: Testes relacionados ao fluxo de registro de usuários
    login: Testes relacionados ao fluxo de login de usuários
    recuperarSenha: Testes relacionados ao fluxo de recuperação de senha dos usuários
    redefinirSenha: Testes relacionados ao fluxo de redefinição de senha dos usuários
